### ISSUE TITLE
Injections incorrectly stretching into Widescreen (16:9)

### ISSUE THREAD

**Issue by NecroNovaVGitHub** [CatmanFan/FriishProduce#31]
I've been experimenting with this tool for quite some time now, and one major issue i've come across during the injections i've made is that most injections have been stretching to 16:9, instead of the proper 4:3 the Official Virtual Console titles use.

This stretching issue has happened across many titles i've injected, and while some injects HAVE gotten into 4:3, others seem completely stuck on 16:9. I've seen the issue occur on both real hardware (vWii), and the Dolphin Emulator. This also happens across ALL the consoles within the Programs lineup. I'm not sure if its something within the code of the Emulators, or if its a Video Issue with the console itself, but if this is addressable, id like to know to figure out what's causing this.

![GithubStretchError#1](https://github.com/CatmanFan/FriishProduce/assets/137644876/bb3856a5-bcef-4cf3-868d-5d6212044106)
[Example 1, tested via Dolphin]

![GithubStretchError#2](https://github.com/CatmanFan/FriishProduce/assets/137644876/0c4ae595-32ee-4f77-ae2f-6e9e6810881b)
[Example 2, tested via the vWii on Wii U]

**Comment by saulfabregwiivc** [comment]
Those are related to the code on the internal Virtual Console (VC) emulators.

Sorry but we don't know how to fix this issue since it's present on all official and injected VC games, but a temporary solution is setting your Wii/Wii U vWii/Dolphin to the screen mode 4:3.

**Comment by gitandrew07** [comment]
i think this app should work: https://github.com/DarkMatterCore/ww-43db-patcher
