### ISSUE TITLE
[Question] any chance for make the database.json to be an editable external file again like in legacy FriishProduce?

### ISSUE THREAD

**Issue by saulfabregwiivc** [CatmanFan/FriishProduce#41]
like the title says, is there a chance for make the new database.json file to be as an editable external file, like we had on legacy FriishProduce?
I like that part on legacy because here i could test adding and testing more base WADs to FriishProduce without having to recompile the program everytime.
Thanks.

**Comment by CatmanFan** [comment]
I could add the option as a checkbox, so that it can be set from within the app, and make it so that it is only available when compiling as Debug (not Release)

**Comment by CatmanFan** [comment]
Already done now, see commit [0cb78214](https://github.com/CatmanFan/FriishProduce/commit/0cb782142d46eb2f3efc1706195d15075e33482c)
