### ISSUE TITLE
Kirby's Adventure Injects not working

### ISSUE THREAD

**Issue by RollPlayStation** [CatmanFan/FriishProduce#44]
I've greatly enjoyed the program, but I'm having trouble injecting roms into the US Wad of Kirby's Adventure. No matter which game I inject and what I follow by the compatibility list, they all result in a black screen. I usually test the injects on Dolphin to make sure they'll work on my Wii U, but any reason why Kirby's Adventure seems to keep producing the same issue? Thanks.

**Comment by RollPlayStation** [comment]
Fixing the NAND seems to have solved the issue.

**Comment by RollPlayStation** [comment]
![image](https://github.com/CatmanFan/FriishProduce/assets/147696934/0ce28571-22fd-4176-a135-0fd1d2bddedc)

**Comment by saulfabregwiivc** [comment]
Which version of FriishProduce are you using?

**Comment by RollPlayStation** [comment]
v1.2.1

**Comment by RollPlayStation** [comment]
Tried a different version of the rom, and now the inject works. FriishProduce must be really sensitive to No-Intro NES roms, particularly with Kirby's Adventure.
