### ISSUE TITLE
Custom WAD compatibility unrecognised

### ISSUE THREAD

**Issue by RollPlayStation** [CatmanFan/FriishProduce#45]
I had a little tamper with the database.json file to add some new games for injection, namely for the SNES and Mega Drive. But I'm not sure if I'm missing something, because despite adding the WAD title ID and Hex correctly, I get an error saying the injection wasn't complete due to files unable to be replaced. Is there something I'm missing? I've listed which games I've tried to add. Does FriishProduce not support LZH8 WADs yet?
![image](https://github.com/CatmanFan/FriishProduce/assets/147696934/93e1b5b9-ba6c-404d-bb4d-be022fca9e11)

**Comment by CatmanFan** [comment]
Hello, sincere apologies for this since I haven't actually clarified this issue before, but yeah, I still haven't added support for LZH8. I guess that I didn't make it clear enough when I was writing instructions for the database.json
